server {
    access_log /var/log/nginx/back-access.log;
    error_log /var/log/nginx/back-error.log;
    root /var/www/html/www.facelandclinic.com/web;
    server_name www.facelandclinic.com.devbox;

    # enable gzip compression
    gzip on;
    gzip_min_length 1100;
    gzip_buffers 4 32k;
    gzip_types text/plain text/javascript application/javascript application/x-javascript text/xml text/css;
    gzip_vary on;
    # end gzip configuration

    location ~* \.(eot|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
    }

    rewrite ^/assets/(.*) /app/themes/faceland/resources/assets/$1;
    rewrite ^/plugins/(.*) /app/plugins/$1;
    rewrite ^/mu-plugins/(.*) /app/mu-plugins/$1;
    location /plugins {
        rewrite ^/plugins/(.*) /app/plugins/$1;
    }

    location /mu-plugins{
        rewrite ^/mu-plugins/(.*) /app/mu-plugins/$1;
    }

    location /login {
        rewrite ^/login/?$ /wp-login.php;
    }

    if (!-e $request_filename) {
        set $test P;
    }
    if ($uri !~ ^/(plesk-stat|webstat|webstat-ssl|ftpstat|anon_ftpstat|awstats-icon|internal-nginx-static-location)) {
        set $test "${test}C";
    }
    if ($test = PC) {
        rewrite ^/(.*)$ /index.php?$1;
    }

    index index.php;
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~* \.php$ {
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_pass php:9000;
    }
    location ~*  \.(pdf|css|html|js|swf)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }     
}